// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odeowcofgyxfjuvxmnwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZW93Y29mZ3l4Zmp1dnhtbnduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzIyMjksImV4cCI6MjA3MTgwODIyOX0.a3w6j3Sh2VseCvMsqde12KZNFSZft21lSwVa8ZCeslI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});